### PR TITLE
feature/Added no-color env support

### PR DESCRIPTION
**Pull request by VasylLymych**
Issue: https://github.com/gios/gzipper/issues/98

### CODE REVIEW

**Comment by gios** [comment]
@VasylLymych Thanks a lot for your PR, a couple of additions.
- use predefined `prettier` and `eslint` configuration in order not to change the default formatting
- if you want to add an additional ENV variable you have to add this functionality to CLI args as well
- update `CHANGELOG.md`, `README.md` and increase the version in `package,json`
- write tests for this additional argument

You can check this PR as an example [PR](https://github.com/gios/gzipper/pull/89/files)

**Comment by VasylLymych** [comment]
> @VasylLymych Thanks a lot for your PR, a couple of additions.
> 
> * use predefined `prettier` and `eslint` configuration in order not to change the default formatting
> * if you want to add an additional ENV variable you have to add this functionality to CLI args as well
> * update `CHANGELOG.md`, `README.md` and increase the version in `package,json`
> * write tests for this additional argument
> 
> You can check this PR as an example [PR](https://github.com/gios/gzipper/pull/89/files)

Sorry i missed your comment) Done

**Comment by emzet** [comment]
@VasylLymych good job, thanks. @gios when you expect to merged and release a new version?

**Comment by gios** [comment]
> @VasylLymych good job, thanks. @gios when you expect to merge and release a new version?

Sorry for the very `long` response, created PR for this https://github.com/gios/gzipper/pull/100, will be merged and published soon a new version.

**Pull request closed without merging**
